### ISSUE TITLE
Can't create more than max_prepared_stmt_count statements

### ISSUE THREAD

**Issue by bsanders1979** [RDBI/rdbi-driver-mysql#5]
In my script, I'm caching the results of Database.execute. Script runs, then craps out because of the above message. If I try calling Result.finish, I get this error:

/usr/local/lib/ruby/gems/1.9.1/gems/rdbi-driver-mysql-0.9.2/lib/rdbi/driver/mysql.rb:329:in free_result': Mysql::Stmt object is already closed (Mysql::Error)
from /usr/local/lib/ruby/gems/1.9.1/gems/rdbi-driver-mysql-0.9.2/lib/rdbi/driver/mysql.rb:329:infinish'
from /usr/local/lib/ruby/gems/1.9.1/gems/rdbi-0.9.1/lib/rdbi/result.rb:279:in `finish'

Perhaps I'm doing something wrong? Suggestions? Thanks!

**Comment by bsanders1979** [comment]
I think the issue may actually lie in the generic rdbi module. When finish is called, it releases the statement, followed by the data, but it seems that the order should be reversed.

**Comment by bsanders1979** [comment]
Yeah, I don't think this is your issue

**Comment by pbennett** [comment]
I'm seeing the exact same issue, just running _tons_ of individual selects.  It's like db.execute('select xxx').fetch(:first) followed by another db.execute('select xxxx') is creating new prepared statements for every single call and not closing the 'prepared' statement when another statement is executed or all rows are fetched.

**Comment by bsanders1979** [comment]
When executing queries, it is in your best interest to use binders for the ones that are similar (ie. generated SQL, or when executing the same statement with different values). As indicated previously, I believe the RDBI module needs to be modified to release the data followed by the statement. With the MySQL driver, the statement is released which in turn releases the data. Then, the code attempts to re-release the data which causes the error.

**Comment by pbennett** [comment]
This is just having to run the same queries over and over with different results for a large data processing task.  RDBI is absolutely broken here - I shouldn't have to change anything for basic select statements to work.  This all works in DBI, yet so far in RDBI, I've run into it not handling datetime values properly (can't insert into a table what rdbi just fetched from the same table) in mysql, and now just running a bunch of queries it chokes.

**Comment by bsanders1979** [comment]
DBI is pretty broken as well (and is not going to be fixed) which is why I dumped it and moved to RDBI which, in my opinion, is waaay better. Contrary to the documentation for RDBI::Database.execute(), the code does not appear to actually finish the statement (but I could be wrong). If you finish the statement, then I believe you lose the result set. As for the dates, the one issue I've run into was where the field contained all zeroes which didn't translate well to Ruby. Where the blame lies is debatable, but I've opened an issue for that as well.

**Comment by pbennett** [comment]
This simple issue alone makes rdbi completely broken.  dbi with select_one or select_all just works and something that works fine with dbi breaks in rdbi just doing an apparently straight translation.
rdbi just has 'execute' for everything.  If users are expected to turn:
rows = db.select_all('select xxxx where ...', xx, yyy)
into
res = db.execute('select xxxx where ...', xx, yyy)
rows = res.fetch(:all)
res.finish
and we're supposed to see that as being way better than dbi then I strongly disagree - particularly if you're saying we have to 'finish' every result set.  I should be able to just use rows = db.execute('select xxxx').fetch(:all) and that should be able to be be run tens of thousands of times without a problem.

**Comment by pbennett** [comment]
As for the dates - I get this [as I commented on another 'closed' issue that wasn't fixed for me either] with mysql:
d:/ruby/lib/ruby/gems/1.9.1/gems/rdbi-driver-mysql-0.9.2/lib/rdbi/driver/mys
ql.rb:408:in `execute': Incorrect datetime value: '2006-02-09 18:07:27 -0500' for column 'created_at' at row 1
 (Mysql::Error)

This is just with me fetching a datetime value in a select and immediately using it in an insert statement into a different table with the exact schema.

**Comment by bsanders1979** [comment]
I have to disagree with the statement that RDBI is broken. To be honest, Ruby DBI is severely handicapped and this link explains why: http://rubyforge.org/forum/forum.php?forum_id=958&style=nested. Basically, if you try to store the result of a query (as opposed to immediately iterating thru it) what you actually get is N rows of rows[-1]. Each element is a distinct object, but they all obviously point to a common object on the heap. The issue is not going to be fixed either, so my only option was to dump it and look for another solution. I discovered RDBI and was instantly hooked. The transition was super easy as I abstracted most of the logic and only had to change a few functions. In short, I developed an engine to archive record trees from one database to another. To do that, I implemented query caching so that I don't have to send the same query to the database to get the same result. I must say that RDBI is actually a well-designed piece of work, but there is definitely room for improvement. After all, it's not even 1.0 yet. I am an end-user just like you are, but I'm telling you about my experience with the library. As for the date issue, you might need to dig thru the code to see what's going on. You might take a look at manipulate_type_maps and see if that has anything to do with it. I had to modify my version to return nil when rescuing an ArgumentError which indicates that the value is not parseable (for the all-zero datetime issue). I did try: DateTime.parse("2006-02-09 18:07:27 -0500") in irb and it worked without issue, so it's hard to say what exactly your problem is. One last thing, if you'd like, I could send you a script template I designed to help get you started with RDBI.

**Comment by pbennett** [comment]
Based on this exact issue, "Can't create more than max_prepared_stmt_count statements" - rdbi is most definitely broken - certainly at least with mysql.
If running tons of independent selects causes rdbi to choke with mysql as it is with me, it's broken - plain and simple.  It's design could be the best in the world but if it can't even run a bunch of queries - who cares.
Using rdbi to fetch a value from the table and then insert that exact same just-fetched value into an identical table and that failing?  broken.
Perhaps it's a 1.9 compatibility issue - not sure.

**Comment by bsanders1979** [comment]
It's not exactly an RDBI issue. It's a mysql setting. If you have a query: select \* from users where password = 'blah', it's better to write it as "select \* from users where password = ?". By taking this approach, you only need 1 prepared statement and can execute many times using different binds. If you do it the unsafe way (ie. "... pasword = '#{password}'"), then you will need at least 1 prepared statement per password. The only issue I see with RDBI (not the mysql driver) is that it's not calling finish on the statement handle when you pass a block to it.

**Comment by pbennett** [comment]
It has nothing at all to do with not using parameter binding - which I use...  I'll just open my own issue for it.
